name: MultiKillSS
main: me.crafter.mc.multikillss.MultiKillSS
version: 3.0
description: >
             Killing Spree plugin, custom death messages.
commands:
   iteminfos:
      permission: multikillss.basic
      usage: |
         /iteminfos
   mkdebug:
      permission: multikillss.admin
      usage: |
         /mkdebug